import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const translations = {
  pt: {
    // ============================================================
    // GERAL / Navegação / Botões
    // ============================================================
    ok: 'OK',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'Salvar',
    save_preferences: 'Salvar Preferências',
    edit: 'Editar',
    delete: 'Excluir',
    search: 'Buscar',
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    warning: 'Atenção',
    info: 'Informação',
    close: 'Fechar',
    back: 'Voltar',
    continue: 'Continuar',
    skip: 'Pular',
    retry: 'Tentar novamente',
    logout: 'Sair',
    refresh: 'Atualizar',
    loading_text: 'Carregando dados...',
    no_results: 'Nenhum resultado encontrado',
    network_error: 'Falha na conexão. Verifique sua internet.',
    generic_error: 'Algo deu errado. Tente novamente.',
    preferences_saved_title: 'Preferências Salvas',
    preferences_saved_message: 'Preferências atualizadas com sucesso',

    // ============================================================
    // Tela de Idioma
    // ============================================================
    language_screen_title: 'Idioma',
    language_screen_header: 'IDIOMA',
    language_screen_subtitle: 'Escolha o idioma do aplicativo. A mudança é aplicada imediatamente.',
    language_pt: 'Português',
    language_en: 'English',
    language_es: 'Español',
    language_applied_title: 'Idioma Alterado',
    language_applied_message: 'O idioma agora é Português',

    // ============================================================
    // Tela Inicial (InitialScreen)
    // ============================================================
    initial_cta_login: 'ENTRAR',
    initial_cta_register: 'CADASTRAR',
    initial_tagline_1: 'Diagnóstico inteligente',
    initial_tagline_2: 'e manutenção preditiva',
    initial_tagline_3: 'para o seu veículo',

    // ============================================================
    // Login / Cadastro / Recuperação
    // ============================================================
    login_title: 'ENTRAR NA CONTA',
    login_email_label: 'Email',
    login_email_placeholder: 'Digite seu email',
    login_password_label: 'Senha',
    login_password_placeholder: 'Digite sua senha',
    login_cta: 'ENTRAR',
    login_forgot: 'Esqueci minha senha',
    login_no_account: 'Não tem conta?',
    login_register_link: 'Cadastre-se',
    login_success: 'Login realizado com sucesso',
    login_error_generic: 'Erro ao realizar login. Verifique suas credenciais.',
    login_invalid_email: 'Por favor, insira um email válido',
    login_invalid_password: 'A senha é obrigatória',

    register_title: 'CRIAR CONTA',
    register_name_label: 'Nome Completo',
    register_name_placeholder: 'Digite seu nome completo',
    register_email_label: 'Email',
    register_email_placeholder: 'Digite seu email',
    register_phone_label: 'Telefone',
    register_phone_placeholder: '(00) 00000-0000',
    register_password_label: 'Senha',
    register_password_placeholder: 'Crie uma senha forte',
    register_confirm_label: 'Confirmar Senha',
    register_confirm_placeholder: 'Repita a senha',
    register_cta: 'CRIAR CONTA',
    register_has_account: 'Já tem conta?',
    register_login_link: 'Entrar',
    register_success: 'Conta criada com sucesso!',
    register_password_mismatch: 'As senhas não coincidem',
    register_password_short: 'A senha deve ter pelo menos 6 caracteres',
    register_name_required: 'O nome completo é obrigatório',
    register_email_required: 'O email é obrigatório',
    register_invalid_email: 'Por favor, insira um email válido',
    register_user_exists: 'Já existe uma conta com este email',

    forgot_title: 'RECUPERAR SENHA',
    forgot_subtitle: 'Digite o email cadastrado e enviaremos instruções para redefinir sua senha.',
    forgot_email_label: 'Email',
    forgot_email_placeholder: 'Digite seu email',
    forgot_cta: 'ENVIAR INSTRUÇÕES',
    forgot_success_title: 'Email Enviado',
    forgot_success_message: 'Verifique sua caixa de entrada para redefinir a senha.',
    forgot_go_back: 'Voltar para o login',

    // ============================================================
    // Home / Principal
    // ============================================================
    home_welcome_prefix: 'Olá',
    home_maintenance_cta: 'MANUTENÇÃO',
    home_premium_cta: 'EXPERIMENTE PREMIUM',
    home_recommendation_loading: 'Carregando recomendações...',
    home_dashboard_maintenance: 'Checklist de\nManutenção',
    home_dashboard_reports: 'Relatórios',
    home_dashboard_fuel: 'Consumo de\nCombustível',
    home_dashboard_tips: 'Dicas de\nManutenção',
    home_dashboard_parts: 'Catálogo de\nPeças',
    home_dashboard_travel: 'Planejamento\nde Viagem',
    home_dashboard_vehicle: 'Histórico do\nVeículo',
    home_dashboard_obd: 'Diagnóstico\nOBD-II',
    home_no_vehicle_title: 'Sem veículo cadastrado',
    home_no_vehicle_desc: 'Cadastre um veículo para verificar o status',
    home_add_vehicle: 'CADASTRAR VEÍCULO',
    home_edit_vehicle: 'EDITAR VEÍCULO',
    home_profile_photo: 'ALTERAR FOTO',
    home_profile_save: 'SALVAR ALTERAÇÕES',
    home_profile_saving: 'Salvando...',
    home_logout_confirm: 'Deseja realmente sair da conta?',

    // ============================================================
    // Header / Notificações
    // ============================================================
    header_profile_title: 'PERFIL',
    header_profile_name: 'Nome',
    header_profile_email: 'Email',
    header_profile_phone: 'Telefone',
    header_plan_free: 'Plano Gratuito',
    header_plan_premium: 'Plano Premium',
    header_vehicle_info: 'Veículo Principal',
    header_vehicle_none: 'Nenhum veículo cadastrado',
    header_vehicle_add: 'Cadastrar Veículo',
    header_vehicle_edit: 'Editar Veículo',
    header_notif_title: 'NOTIFICAÇÕES',
    header_notif_mark_all: 'Marcar todas como lidas',
    header_notif_empty: 'Nenhuma notificação no momento',
    header_logout_cta: 'SAIR DA CONTA',

    // ============================================================
    // Configurações
    // ============================================================
    settings_title: 'CONFIGURAÇÕES',
    settings_notif_section: 'Notificações',
    settings_notif_disable_all: 'Desativar Todas as Notificações',
    settings_notif_maintenance: 'Lembretes de Manutenção',
    settings_notif_obd: 'Alertas OBD-II',
    settings_notif_fuel: 'Dicas de Combustível',
    settings_notif_tips: 'Dicas e Sugestões',
    settings_notif_milestones: 'Marco e Conquistas',
    settings_notif_reminders: 'Lembretes Programáveis',
    settings_notif_frequency: 'Frequência dos Lembretes',

    settings_premium_section: 'Notificações Premium IA ✨',
    settings_premium_ai_insights: 'Insights Gerados por IA',
    settings_premium_predictive: 'Alertas Preditivos',
    settings_premium_driving: 'Análise de Direção e Economia',
    settings_premium_seasonal: 'Recomendações Sazonais',
    settings_premium_smart_freq: 'Frequência Inteligente (2x mais rápida)',
    settings_premium_regenerate: 'Gerar Novos Insights IA Agora',

    settings_pref_section: 'Preferências',
    settings_pref_biometry: 'Ativar/Desativar Biometria',

    settings_help_section: 'Ajuda e Suporte',
    settings_help_faq: 'FAQ',
    settings_help_language: 'Idioma',

    settings_privacy_section: 'Privacidade e Segurança',
    settings_privacy_location: 'Permitir Localização',
    settings_privacy_terms: 'Política de Termos e Condições',
    settings_privacy_delete: 'Apagar Conta/Apagar Dados',

    settings_delete_title: 'Apagar Conta',
    settings_delete_confirm: 'Tem certeza que deseja excluir sua conta? Todos os seus dados serão apagados permanentemente.',
    settings_delete_final: 'Sim, quero excluir minha conta',
    settings_delete_cancel: 'Manter minha conta',
    settings_delete_success: 'Conta excluída com sucesso',
    settings_delete_error: 'Não foi possível excluir sua conta agora.',

    // ============================================================
    // Veículos
    // ============================================================
    vehicle_reg_title: 'CADASTRAR VEÍCULO',
    vehicle_reg_make: 'Marca',
    vehicle_reg_model: 'Modelo',
    vehicle_reg_year: 'Ano',
    vehicle_reg_mileage: 'Quilometragem (km)',
    vehicle_reg_usage: 'Uso do Veículo',
    vehicle_reg_usage_city: 'Urbano (Cidade)',
    vehicle_reg_usage_highway: 'Rodoviário (Estrada)',
    vehicle_reg_usage_mixed: 'Misto',
    vehicle_reg_usage_work: 'Trabalho',
    vehicle_reg_transmission: 'Transmissão',
    vehicle_reg_manual: 'Manual',
    vehicle_reg_automatic: 'Automático',
    vehicle_reg_cvt: 'CVT',
    vehicle_reg_engine: 'Motorização',
    vehicle_reg_fuel: 'Tipo de Combustível',
    vehicle_reg_license: 'Placa (opcional)',
    vehicle_reg_chassis: 'Chassi (opcional)',
    vehicle_reg_last_oil: 'Última troca de óleo (km)',
    vehicle_reg_last_belt: 'Última troca de correia dentada (km)',
    vehicle_reg_last_brake: 'Última troca de freios (km)',
    vehicle_reg_cta: 'CADASTRAR VEÍCULO',
    vehicle_reg_success: 'Veículo cadastrado com sucesso!',
    vehicle_reg_loading: 'Cadastrando...',
    vehicle_reg_error_required: 'Marca, modelo, ano e motorização são obrigatórios',
    vehicle_reg_year_error: 'O ano do veículo deve ser entre 1980 e 2026',

    vehicle_edit_title: 'EDITAR VEÍCULO',
    vehicle_edit_cta: 'SALVAR ALTERAÇÕES',
    vehicle_edit_saving: 'Salvando...',
    vehicle_edit_success: 'Veículo atualizado com sucesso!',
    vehicle_edit_error: 'Erro ao atualizar veículo',
    vehicle_edit_delete_cta: 'EXCLUIR VEÍCULO',
    vehicle_edit_delete_confirm: 'Tem certeza que deseja excluir este veículo?',
    vehicle_edit_delete_success: 'Veículo excluído com sucesso',

    vehicle_history_title: 'HISTÓRICO DO VEÍCULO',
    vehicle_history_empty: 'Nenhuma manutenção registrada ainda.',
    vehicle_history_add: 'NOVA MANUTENÇÃO',
    vehicle_history_tab_maintenance: 'Manutenção',
    vehicle_history_tab_obd: 'Scans OBD',
    vehicle_history_tab_documents: 'Documentos',
    vehicle_history_next_services: 'Próximos Serviços Recomendados',
    vehicle_history_next_oil: 'Troca de Óleo',
    vehicle_history_next_belt: 'Correia Dentada',
    vehicle_history_next_brake: 'Pastilhas de Freio',
    vehicle_history_km_left: 'Faltam',

    // ============================================================
    // OBD / Diagnóstico
    // ============================================================
    obd_title: 'DIAGNÓSTICO EM TEMPO REAL',
    obd_status_connected: 'Conectado',
    obd_status_disconnected: 'Desconectado',
    obd_connect_cta: 'CONECTAR OBD',
    obd_refresh_data: 'Atualizar Dados',
    obd_disconnect: 'Desconectar',
    obd_realtime: 'DADOS EM TEMPO REAL',
    obd_dtc: 'DIAGNÓSTICO DE FALHAS',
    obd_dtc_read: 'Ler Códigos de Erro',
    obd_dtc_reading: 'Lendo códigos...',
    obd_dtc_found: 'Códigos Encontrados',
    obd_dtc_none: 'Nenhum código de falha detectado',
    obd_consumption: 'CONSUMO E EMISSÕES',
    obd_efficiency: 'Eficiência',
    obd_co2: 'Emissões CO₂',
    obd_short_trim: 'Ajuste Curto',
    obd_long_trim: 'Ajuste Longo',
    obd_platform_error_title: 'Plataforma Não Suportada',
    obd_platform_error_msg: 'A conexão com scanner OBD2 é suportada apenas em dispositivos Android.',
    obd_permission_title: 'Permissão Negada',
    obd_permission_msg: 'As permissões de Bluetooth são necessárias para conectar.',
    obd_connect_success_title: 'Conectado!',
    obd_connect_success_msg: 'Conectado com sucesso a',
    obd_connect_error_title: 'Erro de Conexão',
    obd_connect_error_msg: 'Falha ao conectar. Verifique se o dispositivo está pareado (PIN: 1234, 0000, 7890 ou 1111).',
    obd_disconnected_title: 'Desconectado',
    obd_disconnected_msg: 'Dispositivo desconectado!',
    obd_no_conn_error_title: 'Erro',
    obd_no_conn_error_msg: 'Não conectado a um dispositivo OBD',
    obd_dtc_error_title: 'Erro',
    obd_dtc_error_msg: 'Falha ao ler códigos de erro',
    obd_help_title: 'Como Conectar o Scanner OBD2',
    obd_help_step_1: 'Localize a porta OBD2 do seu veículo',
    obd_help_step_2: 'Com o carro ligado na chave (ignição ligada), espete o scanner na porta.',
    obd_help_step_3: 'Pareie com o dispositivo OBD2 nas configurações Bluetooth do celular.',
    obd_help_step_4: 'Se pedir PIN, tente: 1234, 0000, 7890 ou 1111.',
    obd_help_step_5: 'Volte aqui e clique em CONECTAR OBD.',

    obd_history_title: 'INFORMAÇÕES OBD',
    obd_history_loading: 'Carregando histórico...',
    obd_history_no_vehicle: 'Nenhum veículo cadastrado. Cadastre um veículo para começar a registrar scanners.',
    obd_history_empty: 'Nenhum registro de scanner ainda. Conecte o OBD e leia os códigos de erro para começar a gerar histórico.',
    obd_history_dtc: 'Códigos de Erro',
    obd_history_no_errors: 'Nenhum código de erro detectado neste scan.',
    obd_history_conditions: 'Condições do Veículo no Momento',
    obd_history_no_conditions: 'Nenhuma condição registrada neste scan.',
    obd_history_device: 'Dispositivo',
    obd_history_analyze: 'Analisar com IA',
    obd_history_analyzing: 'Analisando...',
    obd_history_analysis: 'Análise da IA',
    obd_history_abnormal: 'Valores Anômalos',
    obd_history_recommendations: 'Recomendações',
    obd_history_dtc_found_summary: 'código(s) encontrado(s)',

    // ============================================================
    // Manutenção / Checklist
    // ============================================================
    checklist_title: 'CHECKLIST DE MANUTENÇÃO',
    checklist_last_services: 'Últimos Serviços Realizados',
    checklist_next_3: 'Próximos 3 Serviços',
    checklist_air_filter: 'Filtro de Ar',
    checklist_oil: 'Óleo do Motor',
    checklist_brake: 'Pastilhas de Freio',
    checklist_battery: 'Bateria',
    checklist_tire: 'Pneus',
    checklist_coolant: 'Líquido de Arrefecimento',
    checklist_transmission_oil: 'Óleo da Transmissão',
    checklist_fuel_filter: 'Filtro de Combustível',
    checklist_suspension: 'Amortecedores/Suspensão',
    checklist_timing_belt: 'Correia Dentada',
    checklist_done: 'Concluído',
    checklist_upcoming: 'Em Breve',
    checklist_overdue: 'Atrasado',

    // ============================================================
    // Combustível
    // ============================================================
    fuel_title: 'CONSUMO DE COMBUSTÍVEL',
    fuel_total_spent: 'Total Gasto',
    fuel_total_liters: 'Litros Abastecidos',
    fuel_avg_efficiency: 'Eficiência Média',
    fuel_top_ups: 'Abastecimentos',
    fuel_add: 'NOVO ABASTECIMENTO',
    fuel_date: 'Data',
    fuel_liters: 'Litros',
    fuel_price: 'Preço/Litro',
    fuel_total: 'Total',
    fuel_full_tank: 'Tanque Cheio',
    fuel_save: 'SALVAR',
    fuel_empty: 'Nenhum abastecimento registrado ainda.',
    fuel_avg_km_per_l: 'km/L',

    // ============================================================
    // Relatórios
    // ============================================================
    report_title: 'RELATÓRIOS DE MANUTENÇÃO',
    report_subtitle: 'Histórico completo de serviços e peças',
    report_add: 'NOVO RELATÓRIO',
    report_edit: 'Editar Relatório',
    report_delete_confirm: 'Excluir este relatório?',
    report_service_type: 'Tipo de Serviço',
    report_description: 'Descrição',
    report_date: 'Data',
    report_cost: 'Custo Total (R$)',
    report_odometer: 'Quilometragem (km)',
    report_receipt: 'Comprovante (opcional)',
    report_notes: 'Anotações',
    report_garage: 'Oficina/Mecânico',
    report_save: 'SALVAR RELATÓRIO',
    report_saving: 'Salvando...',
    report_success: 'Relatório salvo com sucesso!',
    report_edit_success: 'Relatório atualizado com sucesso!',
    report_delete_success: 'Relatório excluído com sucesso',
    report_empty: 'Nenhum relatório cadastrado. Adicione seu primeiro serviço!',
    report_filter: 'Filtrar',
    report_total_cost: 'Total Gasto em Manutenção',
    report_services_count: 'Total de Serviços',

    // ============================================================
    // Peças / Dicas
    // ============================================================
    parts_title: 'CATÁLOGO DE PEÇAS',
    parts_search: 'Buscar peça...',
    parts_empty: 'Nenhuma peça encontrada',
    parts_filter_all: 'Todas',
    parts_filter_engine: 'Motor',
    parts_filter_brake: 'Freios',
    parts_filter_suspension: 'Suspensão',
    parts_filter_filters: 'Filtros',
    parts_filter_electrical: 'Elétrica',
    parts_filter_body: 'Carroceria',
    parts_filter_transmission: 'Transmissão',

    tips_title: 'DICAS DE MANUTENÇÃO',
    tips_read_more: 'Ler mais',

    // ============================================================
    // Premium / Pagamentos
    // ============================================================
    premium_title: 'CONHEÇA O PLANO PREMIUM',
    premium_tagline: 'Desbloqueie todo o poder da IA no seu veículo',
    premium_plan_monthly: 'Plano Mensal',
    premium_plan_yearly: 'Plano Anual',
    premium_save_pct: 'Economize 20%',
    premium_cta: 'ASSINAR AGORA',
    premium_cta_free: 'CONTINUAR GRATUITO',
    premium_feature_1: 'Insights ilimitados de IA',
    premium_feature_2: 'Alertas preditivos de falhas',
    premium_feature_3: 'Análise completa de direção',
    premium_feature_4: 'Recomendações sazonais',
    premium_feature_5: 'Frequência de notificações acelerada',
    premium_feature_6: 'Sem anúncios',
    premium_confirm_title: 'Confirmar Assinatura',
    premium_confirm_msg: 'Deseja confirmar a assinatura do plano Premium?',
    premium_success: 'Parabéns! Você agora é Premium.',

    payment_title: 'FORMAS DE PAGAMENTO',
    payment_credit: 'Cartão de Crédito',
    payment_debit: 'Cartão de Débito',
    payment_pix: 'PIX / QR Code',
    payment_credit_title: 'Pagamento com Crédito',
    payment_debit_title: 'Pagamento com Débito',
    payment_qr_title: 'Pagamento via PIX',
    payment_processing: 'Processando...',
    payment_success_title: 'Pagamento Aprovado',
    payment_success_msg: 'Sua assinatura foi ativada com sucesso!',
    payment_error_title: 'Pagamento Recusado',
    payment_error_msg: 'Não foi possível concluir o pagamento. Tente novamente.',

    // ============================================================
    // Viagens
    // ============================================================
    travel_title: 'PLANEJAMENTO DE VIAGEM',
    travel_route: 'Rota',
    travel_origin: 'Origem',
    travel_destination: 'Destino',
    travel_distance: 'Distância',
    travel_estimate_cost: 'Custo Estimado',
    travel_estimate_fuel: 'Combustível Estimado',
    travel_estimate_time: 'Tempo Estimado',
    travel_cta: 'CALCULAR ROTA',
    travel_checklist_title: 'Checklist de Viagem',
    travel_hint: 'Dica: Verifique óleo, pneus e água antes de sair.',

    trip_title: 'HISTÓRICO DE VIAGENS',
    trip_empty: 'Nenhuma viagem registrada ainda.',

    // ============================================================
    // Navegação Inferior (BottomNav)
    // ============================================================
    nav_home: 'Início',
    nav_report: 'Relatórios',
    nav_fuel: 'Combustível',
    nav_obd: 'OBD',
    nav_settings: 'Config',
  },

  en: {
    ok: 'OK',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    save_preferences: 'Save Preferences',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    close: 'Close',
    back: 'Back',
    continue: 'Continue',
    skip: 'Skip',
    retry: 'Try again',
    logout: 'Log out',
    refresh: 'Refresh',
    loading_text: 'Loading data...',
    no_results: 'No results found',
    network_error: 'Connection failed. Check your internet.',
    generic_error: 'Something went wrong. Please try again.',
    preferences_saved_title: 'Preferences Saved',
    preferences_saved_message: 'Preferences updated successfully',

    language_screen_title: 'Language',
    language_screen_header: 'LANGUAGE',
    language_screen_subtitle: 'Choose the app language. Changes apply immediately.',
    language_pt: 'Português',
    language_en: 'English',
    language_es: 'Español',
    language_applied_title: 'Language Changed',
    language_applied_message: 'The app language is now English',

    initial_cta_login: 'SIGN IN',
    initial_cta_register: 'SIGN UP',
    initial_tagline_1: 'Smart diagnostics',
    initial_tagline_2: 'and predictive maintenance',
    initial_tagline_3: 'for your vehicle',

    login_title: 'SIGN IN',
    login_email_label: 'Email',
    login_email_placeholder: 'Enter your email',
    login_password_label: 'Password',
    login_password_placeholder: 'Enter your password',
    login_cta: 'SIGN IN',
    login_forgot: 'Forgot my password',
    login_no_account: "Don't have an account?",
    login_register_link: 'Sign up',
    login_success: 'Signed in successfully',
    login_error_generic: 'Error signing in. Please check your credentials.',
    login_invalid_email: 'Please enter a valid email',
    login_invalid_password: 'Password is required',

    register_title: 'CREATE ACCOUNT',
    register_name_label: 'Full Name',
    register_name_placeholder: 'Enter your full name',
    register_email_label: 'Email',
    register_email_placeholder: 'Enter your email',
    register_phone_label: 'Phone',
    register_phone_placeholder: '(00) 00000-0000',
    register_password_label: 'Password',
    register_password_placeholder: 'Create a strong password',
    register_confirm_label: 'Confirm Password',
    register_confirm_placeholder: 'Re-enter your password',
    register_cta: 'CREATE ACCOUNT',
    register_has_account: 'Already have an account?',
    register_login_link: 'Sign in',
    register_success: 'Account created successfully!',
    register_password_mismatch: 'Passwords do not match',
    register_password_short: 'Password must be at least 6 characters',
    register_name_required: 'Full name is required',
    register_email_required: 'Email is required',
    register_invalid_email: 'Please enter a valid email',
    register_user_exists: 'An account with this email already exists',

    forgot_title: 'RESET PASSWORD',
    forgot_subtitle: 'Enter your registered email and we will send instructions to reset your password.',
    forgot_email_label: 'Email',
    forgot_email_placeholder: 'Enter your email',
    forgot_cta: 'SEND INSTRUCTIONS',
    forgot_success_title: 'Email Sent',
    forgot_success_message: 'Please check your inbox to reset your password.',
    forgot_go_back: 'Back to sign in',

    home_welcome_prefix: 'Hi',
    home_maintenance_cta: 'MAINTENANCE',
    home_premium_cta: 'TRY PREMIUM',
    home_recommendation_loading: 'Loading recommendations...',
    home_dashboard_maintenance: 'Maintenance\nChecklist',
    home_dashboard_reports: 'Reports',
    home_dashboard_fuel: 'Fuel\nConsumption',
    home_dashboard_tips: 'Maintenance\nTips',
    home_dashboard_parts: 'Parts\nCatalog',
    home_dashboard_travel: 'Travel\nPlanning',
    home_dashboard_vehicle: 'Vehicle\nHistory',
    home_dashboard_obd: 'OBD-II\nDiagnostics',
    home_no_vehicle_title: 'No vehicle registered',
    home_no_vehicle_desc: 'Register a vehicle to check its status',
    home_add_vehicle: 'REGISTER VEHICLE',
    home_edit_vehicle: 'EDIT VEHICLE',
    home_profile_photo: 'CHANGE PHOTO',
    home_profile_save: 'SAVE CHANGES',
    home_profile_saving: 'Saving...',
    home_logout_confirm: 'Are you sure you want to log out?',

    header_profile_title: 'PROFILE',
    header_profile_name: 'Name',
    header_profile_email: 'Email',
    header_profile_phone: 'Phone',
    header_plan_free: 'Free Plan',
    header_plan_premium: 'Premium Plan',
    header_vehicle_info: 'Primary Vehicle',
    header_vehicle_none: 'No vehicle registered',
    header_vehicle_add: 'Register Vehicle',
    header_vehicle_edit: 'Edit Vehicle',
    header_notif_title: 'NOTIFICATIONS',
    header_notif_mark_all: 'Mark all as read',
    header_notif_empty: 'No notifications at the moment',
    header_logout_cta: 'SIGN OUT',

    settings_title: 'SETTINGS',
    settings_notif_section: 'Notifications',
    settings_notif_disable_all: 'Disable All Notifications',
    settings_notif_maintenance: 'Maintenance Reminders',
    settings_notif_obd: 'OBD-II Alerts',
    settings_notif_fuel: 'Fuel Tips',
    settings_notif_tips: 'Tips & Suggestions',
    settings_notif_milestones: 'Milestones & Achievements',
    settings_notif_reminders: 'Programmable Reminders',
    settings_notif_frequency: 'Reminder Frequency',

    settings_premium_section: 'Premium AI Notifications ✨',
    settings_premium_ai_insights: 'AI-Generated Insights',
    settings_premium_predictive: 'Predictive Alerts',
    settings_premium_driving: 'Driving & Economy Analysis',
    settings_premium_seasonal: 'Seasonal Recommendations',
    settings_premium_smart_freq: 'Smart Frequency (2x faster)',
    settings_premium_regenerate: 'Generate New AI Insights Now',

    settings_pref_section: 'Preferences',
    settings_pref_biometry: 'Enable/Disable Biometrics',

    settings_help_section: 'Help & Support',
    settings_help_faq: 'FAQ',
    settings_help_language: 'Language',

    settings_privacy_section: 'Privacy & Security',
    settings_privacy_location: 'Allow Location',
    settings_privacy_terms: 'Terms of Service Policy',
    settings_privacy_delete: 'Delete Account / Delete Data',

    settings_delete_title: 'Delete Account',
    settings_delete_confirm: 'Are you sure you want to delete your account? All your data will be permanently erased.',
    settings_delete_final: 'Yes, delete my account',
    settings_delete_cancel: 'Keep my account',
    settings_delete_success: 'Account deleted successfully',
    settings_delete_error: 'Unable to delete your account right now.',

    vehicle_reg_title: 'REGISTER VEHICLE',
    vehicle_reg_make: 'Brand',
    vehicle_reg_model: 'Model',
    vehicle_reg_year: 'Year',
    vehicle_reg_mileage: 'Mileage (km)',
    vehicle_reg_usage: 'Vehicle Usage',
    vehicle_reg_usage_city: 'Urban (City)',
    vehicle_reg_usage_highway: 'Highway',
    vehicle_reg_usage_mixed: 'Mixed',
    vehicle_reg_usage_work: 'Work',
    vehicle_reg_transmission: 'Transmission',
    vehicle_reg_manual: 'Manual',
    vehicle_reg_automatic: 'Automatic',
    vehicle_reg_cvt: 'CVT',
    vehicle_reg_engine: 'Engine Type',
    vehicle_reg_fuel: 'Fuel Type',
    vehicle_reg_license: 'License Plate (optional)',
    vehicle_reg_chassis: 'Chassis (optional)',
    vehicle_reg_last_oil: 'Last oil change (km)',
    vehicle_reg_last_belt: 'Last timing belt change (km)',
    vehicle_reg_last_brake: 'Last brake change (km)',
    vehicle_reg_cta: 'REGISTER VEHICLE',
    vehicle_reg_success: 'Vehicle registered successfully!',
    vehicle_reg_loading: 'Registering...',
    vehicle_reg_error_required: 'Brand, model, year and engine type are required',
    vehicle_reg_year_error: 'Vehicle year must be between 1980 and 2026',

    vehicle_edit_title: 'EDIT VEHICLE',
    vehicle_edit_cta: 'SAVE CHANGES',
    vehicle_edit_saving: 'Saving...',
    vehicle_edit_success: 'Vehicle updated successfully!',
    vehicle_edit_error: 'Error updating vehicle',
    vehicle_edit_delete_cta: 'DELETE VEHICLE',
    vehicle_edit_delete_confirm: 'Are you sure you want to delete this vehicle?',
    vehicle_edit_delete_success: 'Vehicle deleted successfully',

    vehicle_history_title: 'VEHICLE HISTORY',
    vehicle_history_empty: 'No maintenance records yet.',
    vehicle_history_add: 'NEW MAINTENANCE',
    vehicle_history_tab_maintenance: 'Maintenance',
    vehicle_history_tab_obd: 'OBD Scans',
    vehicle_history_tab_documents: 'Documents',
    vehicle_history_next_services: 'Next Recommended Services',
    vehicle_history_next_oil: 'Oil Change',
    vehicle_history_next_belt: 'Timing Belt',
    vehicle_history_next_brake: 'Brake Pads',
    vehicle_history_km_left: 'Remaining',

    obd_title: 'REAL-TIME DIAGNOSTICS',
    obd_status_connected: 'Connected',
    obd_status_disconnected: 'Disconnected',
    obd_connect_cta: 'CONNECT OBD',
    obd_refresh_data: 'Refresh Data',
    obd_disconnect: 'Disconnect',
    obd_realtime: 'REAL-TIME DATA',
    obd_dtc: 'FAULT DIAGNOSTICS',
    obd_dtc_read: 'Read Trouble Codes',
    obd_dtc_reading: 'Reading codes...',
    obd_dtc_found: 'Codes Found',
    obd_dtc_none: 'No trouble codes detected',
    obd_consumption: 'FUEL & EMISSIONS',
    obd_efficiency: 'Efficiency',
    obd_co2: 'CO₂ Emissions',
    obd_short_trim: 'Short Term Trim',
    obd_long_trim: 'Long Term Trim',
    obd_platform_error_title: 'Unsupported Platform',
    obd_platform_error_msg: 'OBD2 scanner connection is only supported on Android devices.',
    obd_permission_title: 'Permission Denied',
    obd_permission_msg: 'Bluetooth permissions are required to connect.',
    obd_connect_success_title: 'Connected!',
    obd_connect_success_msg: 'Successfully connected to',
    obd_connect_error_title: 'Connection Error',
    obd_connect_error_msg: 'Failed to connect. Make sure the device is paired (PIN: 1234, 0000, 7890 or 1111).',
    obd_disconnected_title: 'Disconnected',
    obd_disconnected_msg: 'Device disconnected!',
    obd_no_conn_error_title: 'Error',
    obd_no_conn_error_msg: 'Not connected to an OBD device',
    obd_dtc_error_title: 'Error',
    obd_dtc_error_msg: 'Failed to read trouble codes',
    obd_help_title: 'How to Connect the OBD2 Scanner',
    obd_help_step_1: 'Locate the OBD2 port in your vehicle',
    obd_help_step_2: 'With the ignition on, plug the scanner into the port.',
    obd_help_step_3: 'Pair with the OBD2 device in your phone Bluetooth settings.',
    obd_help_step_4: 'If asked for PIN, try: 1234, 0000, 7890 or 1111.',
    obd_help_step_5: 'Come back here and click CONNECT OBD.',

    obd_history_title: 'OBD INFORMATION',
    obd_history_loading: 'Loading history...',
    obd_history_no_vehicle: 'No vehicle registered. Register a vehicle to start recording scans.',
    obd_history_empty: 'No scan records yet. Connect the OBD and read trouble codes to build history.',
    obd_history_dtc: 'Trouble Codes',
    obd_history_no_errors: 'No trouble codes detected in this scan.',
    obd_history_conditions: 'Vehicle Conditions at the Time',
    obd_history_no_conditions: 'No conditions recorded in this scan.',
    obd_history_device: 'Device',
    obd_history_analyze: 'Analyze with AI',
    obd_history_analyzing: 'Analyzing...',
    obd_history_analysis: 'AI Analysis',
    obd_history_abnormal: 'Abnormal Values',
    obd_history_recommendations: 'Recommendations',
    obd_history_dtc_found_summary: 'code(s) found',

    checklist_title: 'MAINTENANCE CHECKLIST',
    checklist_last_services: 'Recent Services',
    checklist_next_3: 'Next 3 Services',
    checklist_air_filter: 'Air Filter',
    checklist_oil: 'Engine Oil',
    checklist_brake: 'Brake Pads',
    checklist_battery: 'Battery',
    checklist_tire: 'Tires',
    checklist_coolant: 'Coolant',
    checklist_transmission_oil: 'Transmission Oil',
    checklist_fuel_filter: 'Fuel Filter',
    checklist_suspension: 'Shocks / Suspension',
    checklist_timing_belt: 'Timing Belt',
    checklist_done: 'Done',
    checklist_upcoming: 'Upcoming',
    checklist_overdue: 'Overdue',

    fuel_title: 'FUEL CONSUMPTION',
    fuel_total_spent: 'Total Spent',
    fuel_total_liters: 'Liters Refueled',
    fuel_avg_efficiency: 'Average Efficiency',
    fuel_top_ups: 'Refuels',
    fuel_add: 'NEW REFILL',
    fuel_date: 'Date',
    fuel_liters: 'Liters',
    fuel_price: 'Price/Liter',
    fuel_total: 'Total',
    fuel_full_tank: 'Full Tank',
    fuel_save: 'SAVE',
    fuel_empty: 'No refuels recorded yet.',
    fuel_avg_km_per_l: 'km/L',

    report_title: 'MAINTENANCE REPORTS',
    report_subtitle: 'Complete history of services and parts',
    report_add: 'NEW REPORT',
    report_edit: 'Edit Report',
    report_delete_confirm: 'Delete this report?',
    report_service_type: 'Service Type',
    report_description: 'Description',
    report_date: 'Date',
    report_cost: 'Total Cost ($)',
    report_odometer: 'Mileage (km)',
    report_receipt: 'Receipt (optional)',
    report_notes: 'Notes',
    report_garage: 'Shop / Mechanic',
    report_save: 'SAVE REPORT',
    report_saving: 'Saving...',
    report_success: 'Report saved successfully!',
    report_edit_success: 'Report updated successfully!',
    report_delete_success: 'Report deleted successfully',
    report_empty: 'No reports yet. Add your first service!',
    report_filter: 'Filter',
    report_total_cost: 'Total Spent on Maintenance',
    report_services_count: 'Total Services',

    parts_title: 'PARTS CATALOG',
    parts_search: 'Search part...',
    parts_empty: 'No parts found',
    parts_filter_all: 'All',
    parts_filter_engine: 'Engine',
    parts_filter_brake: 'Brakes',
    parts_filter_suspension: 'Suspension',
    parts_filter_filters: 'Filters',
    parts_filter_electrical: 'Electrical',
    parts_filter_body: 'Body',
    parts_filter_transmission: 'Transmission',

    tips_title: 'MAINTENANCE TIPS',
    tips_read_more: 'Read more',

    premium_title: 'MEET THE PREMIUM PLAN',
    premium_tagline: 'Unlock the full power of AI for your vehicle',
    premium_plan_monthly: 'Monthly Plan',
    premium_plan_yearly: 'Yearly Plan',
    premium_save_pct: 'Save 20%',
    premium_cta: 'SUBSCRIBE NOW',
    premium_cta_free: 'CONTINUE FREE',
    premium_feature_1: 'Unlimited AI insights',
    premium_feature_2: 'Predictive failure alerts',
    premium_feature_3: 'Complete driving analysis',
    premium_feature_4: 'Seasonal recommendations',
    premium_feature_5: 'Faster notification frequency',
    premium_feature_6: 'No ads',
    premium_confirm_title: 'Confirm Subscription',
    premium_confirm_msg: 'Do you want to confirm the Premium plan subscription?',
    premium_success: 'Congratulations! You are now Premium.',

    payment_title: 'PAYMENT METHODS',
    payment_credit: 'Credit Card',
    payment_debit: 'Debit Card',
    payment_pix: 'PIX / QR Code',
    payment_credit_title: 'Pay with Credit',
    payment_debit_title: 'Pay with Debit',
    payment_qr_title: 'Pay via PIX',
    payment_processing: 'Processing...',
    payment_success_title: 'Payment Approved',
    payment_success_msg: 'Your subscription has been activated successfully!',
    payment_error_title: 'Payment Declined',
    payment_error_msg: 'We couldn\'t complete the payment. Please try again.',

    travel_title: 'TRIP PLANNING',
    travel_route: 'Route',
    travel_origin: 'Origin',
    travel_destination: 'Destination',
    travel_distance: 'Distance',
    travel_estimate_cost: 'Estimated Cost',
    travel_estimate_fuel: 'Estimated Fuel',
    travel_estimate_time: 'Estimated Time',
    travel_cta: 'CALCULATE ROUTE',
    travel_checklist_title: 'Trip Checklist',
    travel_hint: 'Tip: Check oil, tires and coolant before you go.',

    trip_title: 'TRIP HISTORY',
    trip_empty: 'No trips recorded yet.',

    nav_home: 'Home',
    nav_report: 'Reports',
    nav_fuel: 'Fuel',
    nav_obd: 'OBD',
    nav_settings: 'Settings',
  },

  es: {
    ok: 'OK',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'Guardar',
    save_preferences: 'Guardar Preferencias',
    edit: 'Editar',
    delete: 'Eliminar',
    search: 'Buscar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    warning: 'Aviso',
    info: 'Información',
    close: 'Cerrar',
    back: 'Volver',
    continue: 'Continuar',
    skip: 'Saltar',
    retry: 'Intentar de nuevo',
    logout: 'Salir',
    refresh: 'Actualizar',
    loading_text: 'Cargando datos...',
    no_results: 'No se encontraron resultados',
    network_error: 'Error de conexión. Revisa tu internet.',
    generic_error: 'Algo salió mal. Inténtalo de nuevo.',
    preferences_saved_title: 'Preferencias Guardadas',
    preferences_saved_message: 'Preferencias actualizadas con éxito',

    language_screen_title: 'Idioma',
    language_screen_header: 'IDIOMA',
    language_screen_subtitle: 'Elige el idioma de la aplicación. Los cambios se aplican inmediatamente.',
    language_pt: 'Português',
    language_en: 'English',
    language_es: 'Español',
    language_applied_title: 'Idioma Cambiado',
    language_applied_message: 'El idioma de la app ahora es Español',

    initial_cta_login: 'INICIAR SESIÓN',
    initial_cta_register: 'REGISTRARSE',
    initial_tagline_1: 'Diagnóstico inteligente',
    initial_tagline_2: 'y mantenimiento predictivo',
    initial_tagline_3: 'para tu vehículo',

    login_title: 'INICIAR SESIÓN',
    login_email_label: 'Correo electrónico',
    login_email_placeholder: 'Ingresa tu correo',
    login_password_label: 'Contraseña',
    login_password_placeholder: 'Ingresa tu contraseña',
    login_cta: 'INICIAR SESIÓN',
    login_forgot: 'Olvidé mi contraseña',
    login_no_account: '¿No tienes cuenta?',
    login_register_link: 'Regístrate',
    login_success: 'Sesión iniciada con éxito',
    login_error_generic: 'Error al iniciar sesión. Revisa tus credenciales.',
    login_invalid_email: 'Por favor ingresa un correo válido',
    login_invalid_password: 'La contraseña es obligatoria',

    register_title: 'CREAR CUENTA',
    register_name_label: 'Nombre Completo',
    register_name_placeholder: 'Ingresa tu nombre completo',
    register_email_label: 'Correo electrónico',
    register_email_placeholder: 'Ingresa tu correo',
    register_phone_label: 'Teléfono',
    register_phone_placeholder: '(00) 00000-0000',
    register_password_label: 'Contraseña',
    register_password_placeholder: 'Crea una contraseña segura',
    register_confirm_label: 'Confirmar Contraseña',
    register_confirm_placeholder: 'Repite la contraseña',
    register_cta: 'CREAR CUENTA',
    register_has_account: '¿Ya tienes cuenta?',
    register_login_link: 'Iniciar sesión',
    register_success: '¡Cuenta creada con éxito!',
    register_password_mismatch: 'Las contraseñas no coinciden',
    register_password_short: 'La contraseña debe tener al menos 6 caracteres',
    register_name_required: 'El nombre completo es obligatorio',
    register_email_required: 'El correo es obligatorio',
    register_invalid_email: 'Por favor ingresa un correo válido',
    register_user_exists: 'Ya existe una cuenta con este correo',

    forgot_title: 'RECUPERAR CONTRASEÑA',
    forgot_subtitle: 'Ingresa tu correo registrado y enviaremos instrucciones para restablecer tu contraseña.',
    forgot_email_label: 'Correo',
    forgot_email_placeholder: 'Ingresa tu correo',
    forgot_cta: 'ENVIAR INSTRUCCIONES',
    forgot_success_title: 'Correo Enviado',
    forgot_success_message: 'Revisa tu bandeja de entrada para restablecer la contraseña.',
    forgot_go_back: 'Volver al inicio de sesión',

    home_welcome_prefix: 'Hola',
    home_maintenance_cta: 'MANTENIMIENTO',
    home_premium_cta: 'PROBAR PREMIUM',
    home_recommendation_loading: 'Cargando recomendaciones...',
    home_dashboard_maintenance: 'Checklist de\nMantenimiento',
    home_dashboard_reports: 'Reportes',
    home_dashboard_fuel: 'Consumo de\nCombustible',
    home_dashboard_tips: 'Consejos de\nMantenimiento',
    home_dashboard_parts: 'Catálogo de\nRepuestos',
    home_dashboard_travel: 'Planificación\nde Viaje',
    home_dashboard_vehicle: 'Historial del\nVehículo',
    home_dashboard_obd: 'Diagnóstico\nOBD-II',
    home_no_vehicle_title: 'Sin vehículo registrado',
    home_no_vehicle_desc: 'Registra un vehículo para verificar su estado',
    home_add_vehicle: 'REGISTRAR VEHÍCULO',
    home_edit_vehicle: 'EDITAR VEHÍCULO',
    home_profile_photo: 'CAMBIAR FOTO',
    home_profile_save: 'GUARDAR CAMBIOS',
    home_profile_saving: 'Guardando...',
    home_logout_confirm: '¿Seguro que deseas cerrar la sesión?',

    header_profile_title: 'PERFIL',
    header_profile_name: 'Nombre',
    header_profile_email: 'Correo',
    header_profile_phone: 'Teléfono',
    header_plan_free: 'Plan Gratuito',
    header_plan_premium: 'Plan Premium',
    header_vehicle_info: 'Vehículo Principal',
    header_vehicle_none: 'Sin vehículo registrado',
    header_vehicle_add: 'Registrar Vehículo',
    header_vehicle_edit: 'Editar Vehículo',
    header_notif_title: 'NOTIFICACIONES',
    header_notif_mark_all: 'Marcar todas como leídas',
    header_notif_empty: 'Sin notificaciones en este momento',
    header_logout_cta: 'CERRAR SESIÓN',

    settings_title: 'CONFIGURACIÓN',
    settings_notif_section: 'Notificaciones',
    settings_notif_disable_all: 'Desactivar Todas las Notificaciones',
    settings_notif_maintenance: 'Recordatorios de Mantenimiento',
    settings_notif_obd: 'Alertas OBD-II',
    settings_notif_fuel: 'Consejos de Combustible',
    settings_notif_tips: 'Consejos y Sugerencias',
    settings_notif_milestones: 'Hitos y Logros',
    settings_notif_reminders: 'Recordatorios Programables',
    settings_notif_frequency: 'Frecuencia de Recordatorios',

    settings_premium_section: 'Notificaciones Premium IA ✨',
    settings_premium_ai_insights: 'Insights Generados por IA',
    settings_premium_predictive: 'Alertas Predictivas',
    settings_premium_driving: 'Análisis de Conducción y Economía',
    settings_premium_seasonal: 'Recomendaciones Estacionales',
    settings_premium_smart_freq: 'Frecuencia Inteligente (2x más rápida)',
    settings_premium_regenerate: 'Generar Nuevos Insights IA Ahora',

    settings_pref_section: 'Preferencias',
    settings_pref_biometry: 'Activar/Desactivar Biometría',

    settings_help_section: 'Ayuda y Soporte',
    settings_help_faq: 'Preguntas Frecuentes',
    settings_help_language: 'Idioma',

    settings_privacy_section: 'Privacidad y Seguridad',
    settings_privacy_location: 'Permitir Ubicación',
    settings_privacy_terms: 'Política de Términos y Condiciones',
    settings_privacy_delete: 'Eliminar Cuenta / Eliminar Datos',

    settings_delete_title: 'Eliminar Cuenta',
    settings_delete_confirm: '¿Seguro que deseas eliminar tu cuenta? Todos tus datos serán borrados permanentemente.',
    settings_delete_final: 'Sí, eliminar mi cuenta',
    settings_delete_cancel: 'Mantener mi cuenta',
    settings_delete_success: 'Cuenta eliminada con éxito',
    settings_delete_error: 'No fue posible eliminar tu cuenta ahora.',

    vehicle_reg_title: 'REGISTRAR VEHÍCULO',
    vehicle_reg_make: 'Marca',
    vehicle_reg_model: 'Modelo',
    vehicle_reg_year: 'Año',
    vehicle_reg_mileage: 'Kilometraje (km)',
    vehicle_reg_usage: 'Uso del Vehículo',
    vehicle_reg_usage_city: 'Urbano (Ciudad)',
    vehicle_reg_usage_highway: 'Carretera',
    vehicle_reg_usage_mixed: 'Mixto',
    vehicle_reg_usage_work: 'Trabajo',
    vehicle_reg_transmission: 'Transmisión',
    vehicle_reg_manual: 'Manual',
    vehicle_reg_automatic: 'Automático',
    vehicle_reg_cvt: 'CVT',
    vehicle_reg_engine: 'Tipo de Motor',
    vehicle_reg_fuel: 'Tipo de Combustible',
    vehicle_reg_license: 'Placa (opcional)',
    vehicle_reg_chassis: 'Chasis (opcional)',
    vehicle_reg_last_oil: 'Último cambio de aceite (km)',
    vehicle_reg_last_belt: 'Último cambio de correa (km)',
    vehicle_reg_last_brake: 'Último cambio de frenos (km)',
    vehicle_reg_cta: 'REGISTRAR VEHÍCULO',
    vehicle_reg_success: '¡Vehículo registrado con éxito!',
    vehicle_reg_loading: 'Registrando...',
    vehicle_reg_error_required: 'Marca, modelo, año y motorización son obligatorios',
    vehicle_reg_year_error: 'El año debe estar entre 1980 y 2026',

    vehicle_edit_title: 'EDITAR VEHÍCULO',
    vehicle_edit_cta: 'GUARDAR CAMBIOS',
    vehicle_edit_saving: 'Guardando...',
    vehicle_edit_success: '¡Vehículo actualizado con éxito!',
    vehicle_edit_error: 'Error al actualizar el vehículo',
    vehicle_edit_delete_cta: 'ELIMINAR VEHÍCULO',
    vehicle_edit_delete_confirm: '¿Seguro que deseas eliminar este vehículo?',
    vehicle_edit_delete_success: 'Vehículo eliminado con éxito',

    vehicle_history_title: 'HISTORIAL DEL VEHÍCULO',
    vehicle_history_empty: 'Sin mantenimientos registrados.',
    vehicle_history_add: 'NUEVO MANTENIMIENTO',
    vehicle_history_tab_maintenance: 'Mantenimiento',
    vehicle_history_tab_obd: 'Scans OBD',
    vehicle_history_tab_documents: 'Documentos',
    vehicle_history_next_services: 'Próximos Servicios Recomendados',
    vehicle_history_next_oil: 'Cambio de Aceite',
    vehicle_history_next_belt: 'Correa de Distribución',
    vehicle_history_next_brake: 'Pastillas de Freno',
    vehicle_history_km_left: 'Faltan',

    obd_title: 'DIAGNÓSTICO EN TIEMPO REAL',
    obd_status_connected: 'Conectado',
    obd_status_disconnected: 'Desconectado',
    obd_connect_cta: 'CONECTAR OBD',
    obd_refresh_data: 'Actualizar Datos',
    obd_disconnect: 'Desconectar',
    obd_realtime: 'DATOS EN TIEMPO REAL',
    obd_dtc: 'DIAGNÓSTICO DE FALLOS',
    obd_dtc_read: 'Leer Códigos de Avería',
    obd_dtc_reading: 'Leyendo códigos...',
    obd_dtc_found: 'Códigos Encontrados',
    obd_dtc_none: 'No se detectaron códigos de avería',
    obd_consumption: 'COMBUSTIBLE Y EMISIONES',
    obd_efficiency: 'Eficiencia',
    obd_co2: 'Emisiones CO₂',
    obd_short_trim: 'Ajuste Corto',
    obd_long_trim: 'Ajuste Largo',
    obd_platform_error_title: 'Plataforma No Compatible',
    obd_platform_error_msg: 'La conexión con escáner OBD2 solo es compatible con Android.',
    obd_permission_title: 'Permiso Denegado',
    obd_permission_msg: 'Los permisos de Bluetooth son necesarios para conectarse.',
    obd_connect_success_title: '¡Conectado!',
    obd_connect_success_msg: 'Conectado con éxito a',
    obd_connect_error_title: 'Error de Conexión',
    obd_connect_error_msg: 'No se pudo conectar. Verifica que el dispositivo esté emparejado (PIN: 1234, 0000, 7890 o 1111).',
    obd_disconnected_title: 'Desconectado',
    obd_disconnected_msg: '¡Dispositivo desconectado!',
    obd_no_conn_error_title: 'Error',
    obd_no_conn_error_msg: 'No hay conexión con un dispositivo OBD',
    obd_dtc_error_title: 'Error',
    obd_dtc_error_msg: 'Fallo al leer códigos de avería',
    obd_help_title: 'Cómo Conectar el Escáner OBD2',
    obd_help_step_1: 'Localiza el puerto OBD2 de tu vehículo',
    obd_help_step_2: 'Con el encendido activado, conecta el escáner.',
    obd_help_step_3: 'Empareja el dispositivo OBD2 en los ajustes Bluetooth.',
    obd_help_step_4: 'Si pide PIN, prueba: 1234, 0000, 7890 o 1111.',
    obd_help_step_5: 'Vuelve aquí y pulsa CONECTAR OBD.',

    obd_history_title: 'INFORMACIÓN OBD',
    obd_history_loading: 'Cargando historial...',
    obd_history_no_vehicle: 'Sin vehículo registrado. Registra un vehículo para empezar a guardar escaneos.',
    obd_history_empty: 'Sin registros de escaneo. Conecta el OBD y lee códigos para generar historial.',
    obd_history_dtc: 'Códigos de Avería',
    obd_history_no_errors: 'Sin códigos de avería en este escaneo.',
    obd_history_conditions: 'Condiciones del Vehículo en el Momento',
    obd_history_no_conditions: 'Sin condiciones registradas en este escaneo.',
    obd_history_device: 'Dispositivo',
    obd_history_analyze: 'Analizar con IA',
    obd_history_analyzing: 'Analizando...',
    obd_history_analysis: 'Análisis de la IA',
    obd_history_abnormal: 'Valores Anómalos',
    obd_history_recommendations: 'Recomendaciones',
    obd_history_dtc_found_summary: 'código(s) encontrado(s)',

    checklist_title: 'CHECKLIST DE MANTENIMIENTO',
    checklist_last_services: 'Servicios Recientes',
    checklist_next_3: 'Próximos 3 Servicios',
    checklist_air_filter: 'Filtro de Aire',
    checklist_oil: 'Aceite del Motor',
    checklist_brake: 'Pastillas de Freno',
    checklist_battery: 'Batería',
    checklist_tire: 'Neumáticos',
    checklist_coolant: 'Refrigerante',
    checklist_transmission_oil: 'Aceite de Transmisión',
    checklist_fuel_filter: 'Filtro de Combustible',
    checklist_suspension: 'Amortiguadores / Suspensión',
    checklist_timing_belt: 'Correa de Distribución',
    checklist_done: 'Hecho',
    checklist_upcoming: 'Próximamente',
    checklist_overdue: 'Vencido',

    fuel_title: 'CONSUMO DE COMBUSTIBLE',
    fuel_total_spent: 'Total Gastado',
    fuel_total_liters: 'Litros Cargados',
    fuel_avg_efficiency: 'Eficiencia Promedio',
    fuel_top_ups: 'Recargas',
    fuel_add: 'NUEVA RECARGA',
    fuel_date: 'Fecha',
    fuel_liters: 'Litros',
    fuel_price: 'Precio/Litro',
    fuel_total: 'Total',
    fuel_full_tank: 'Tanque Lleno',
    fuel_save: 'GUARDAR',
    fuel_empty: 'Sin recargas registradas.',
    fuel_avg_km_per_l: 'km/L',

    report_title: 'INFORMES DE MANTENIMIENTO',
    report_subtitle: 'Historial completo de servicios y repuestos',
    report_add: 'NUEVO INFORME',
    report_edit: 'Editar Informe',
    report_delete_confirm: '¿Eliminar este informe?',
    report_service_type: 'Tipo de Servicio',
    report_description: 'Descripción',
    report_date: 'Fecha',
    report_cost: 'Costo Total ($)',
    report_odometer: 'Kilometraje (km)',
    report_receipt: 'Comprobante (opcional)',
    report_notes: 'Notas',
    report_garage: 'Taller / Mecánico',
    report_save: 'GUARDAR INFORME',
    report_saving: 'Guardando...',
    report_success: '¡Informe guardado con éxito!',
    report_edit_success: '¡Informe actualizado con éxito!',
    report_delete_success: 'Informe eliminado con éxito',
    report_empty: 'Sin informes todavía. ¡Agrega tu primer servicio!',
    report_filter: 'Filtrar',
    report_total_cost: 'Total Gastado en Mantenimiento',
    report_services_count: 'Total de Servicios',

    parts_title: 'CATÁLOGO DE REPUESTOS',
    parts_search: 'Buscar repuesto...',
    parts_empty: 'No se encontraron repuestos',
    parts_filter_all: 'Todos',
    parts_filter_engine: 'Motor',
    parts_filter_brake: 'Frenos',
    parts_filter_suspension: 'Suspensión',
    parts_filter_filters: 'Filtros',
    parts_filter_electrical: 'Eléctrica',
    parts_filter_body: 'Carrocería',
    parts_filter_transmission: 'Transmisión',

    tips_title: 'CONSEJOS DE MANTENIMIENTO',
    tips_read_more: 'Leer más',

    premium_title: 'CONOCE EL PLAN PREMIUM',
    premium_tagline: 'Desbloquea todo el poder de la IA para tu vehículo',
    premium_plan_monthly: 'Plan Mensual',
    premium_plan_yearly: 'Plan Anual',
    premium_save_pct: 'Ahorra 20%',
    premium_cta: 'SUSCRIBIRSE AHORA',
    premium_cta_free: 'CONTINUAR GRATIS',
    premium_feature_1: 'Insights ilimitados de IA',
    premium_feature_2: 'Alertas predictivas de fallos',
    premium_feature_3: 'Análisis completo de conducción',
    premium_feature_4: 'Recomendaciones estacionales',
    premium_feature_5: 'Frecuencia de notificaciones rápida',
    premium_feature_6: 'Sin anuncios',
    premium_confirm_title: 'Confirmar Suscripción',
    premium_confirm_msg: '¿Deseas confirmar la suscripción al plan Premium?',
    premium_success: '¡Felicidades! Ahora eres Premium.',

    payment_title: 'FORMAS DE PAGO',
    payment_credit: 'Tarjeta de Crédito',
    payment_debit: 'Tarjeta de Débito',
    payment_pix: 'PIX / Código QR',
    payment_credit_title: 'Pago con Crédito',
    payment_debit_title: 'Pago con Débito',
    payment_qr_title: 'Pago via PIX',
    payment_processing: 'Procesando...',
    payment_success_title: 'Pago Aprobado',
    payment_success_msg: '¡Tu suscripción ha sido activada con éxito!',
    payment_error_title: 'Pago Rechazado',
    payment_error_msg: 'No fue posible completar el pago. Inténtalo de nuevo.',

    travel_title: 'PLANIFICACIÓN DE VIAJE',
    travel_route: 'Ruta',
    travel_origin: 'Origen',
    travel_destination: 'Destino',
    travel_distance: 'Distancia',
    travel_estimate_cost: 'Costo Estimado',
    travel_estimate_fuel: 'Combustible Estimado',
    travel_estimate_time: 'Tiempo Estimado',
    travel_cta: 'CALCULAR RUTA',
    travel_checklist_title: 'Checklist de Viaje',
    travel_hint: 'Consejo: Revisa aceite, neumáticos y refrigerante antes de salir.',

    trip_title: 'HISTORIAL DE VIAJES',
    trip_empty: 'Sin viajes registrados.',

    nav_home: 'Inicio',
    nav_report: 'Informes',
    nav_fuel: 'Combustible',
    nav_obd: 'OBD',
    nav_settings: 'Config',
  },
};

const STORAGE_KEY = '@amp_language_v1';
export const SUPPORTED_LANGUAGES = ['pt', 'en', 'es'];
export const LANGUAGE_NAMES = {
  pt: { native: 'Português', flag: '🇧🇷' },
  en: { native: 'English', flag: '🇺🇸' },
  es: { native: 'Español', flag: '🇪🇸' },
};

const LanguageContext = createContext();

const resolveKey = (dict, key) => {
  if (!dict) return undefined;
  if (dict[key] !== undefined) return dict[key];
  return undefined;
};

const interpolate = (template, params) => {
  if (typeof template !== 'string' || !params) return template;
  let result = template;
  Object.keys(params).forEach((k) => {
    const v = params[k];
    const val = v === null || v === undefined ? '' : String(v);
    const pattern = new RegExp(`\\{\\{${k}\\}\\}`, 'g');
    result = result.replace(pattern, val);
    const patternSimple = new RegExp(`\\{${k}\\}`, 'g');
    result = result.replace(patternSimple, val);
  });
  return result;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState('pt');
  const [isLoaded, setIsLoaded] = useState(false);

  const availableLanguages = useMemo(() =>
    SUPPORTED_LANGUAGES.map((code) => ({
      code,
      ...LANGUAGE_NAMES[code],
      active: code === language,
    })), [language]);

  useEffect(() => {
    (async () => {
      try {
        const saved = await AsyncStorage.getItem(STORAGE_KEY);
        if (saved && translations[saved]) {
          setLanguageState(saved);
        }
      } catch (e) {
        console.warn('Erro ao carregar idioma salvo:', e);
      } finally {
        setIsLoaded(true);
      }
    })();
  }, []);

  const setLanguage = useCallback(async (langCode) => {
    if (!translations[langCode]) return;
    setLanguageState(langCode);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, langCode);
    } catch (e) {
      console.warn('Erro ao salvar idioma:', e);
    }
  }, []);

  const t = useCallback((key, params) => {
    if (!key) return '';
    let val = resolveKey(translations[language], key);
    if (val === undefined) val = resolveKey(translations['pt'], key);
    if (val === undefined) val = key;
    return interpolate(val, params);
  }, [language]);

  const dir = 'ltr';

  if (!isLoaded) return null;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage precisa ser usado dentro de um <LanguageProvider>');
  }
  return context;
};

export default LanguageContext;
